// Generated by gencpp from file learing/add.msg
// DO NOT EDIT!


#ifndef LEARING_MESSAGE_ADD_H
#define LEARING_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <learing/addRequest.h>
#include <learing/addResponse.h>


namespace learing
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace learing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learing::add > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learing::add&) { return value(); }
};

template<>
struct DataType< ::learing::add > {
  static const char* value()
  {
    return "learing/add";
  }

  static const char* value(const ::learing::add&) { return value(); }
};


// service_traits::MD5Sum< ::learing::addRequest> should match
// service_traits::MD5Sum< ::learing::add >
template<>
struct MD5Sum< ::learing::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learing::add >::value();
  }
  static const char* value(const ::learing::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learing::addRequest> should match
// service_traits::DataType< ::learing::add >
template<>
struct DataType< ::learing::addRequest>
{
  static const char* value()
  {
    return DataType< ::learing::add >::value();
  }
  static const char* value(const ::learing::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learing::addResponse> should match
// service_traits::MD5Sum< ::learing::add >
template<>
struct MD5Sum< ::learing::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learing::add >::value();
  }
  static const char* value(const ::learing::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learing::addResponse> should match
// service_traits::DataType< ::learing::add >
template<>
struct DataType< ::learing::addResponse>
{
  static const char* value()
  {
    return DataType< ::learing::add >::value();
  }
  static const char* value(const ::learing::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARING_MESSAGE_ADD_H
