// Auto-generated. Do not edit!

// (in-package learing.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class kissResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_kiss_kissed = null;
    }
    else {
      if (initObj.hasOwnProperty('total_kiss_kissed')) {
        this.total_kiss_kissed = initObj.total_kiss_kissed
      }
      else {
        this.total_kiss_kissed = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type kissResult
    // Serialize message field [total_kiss_kissed]
    bufferOffset = _serializer.uint32(obj.total_kiss_kissed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type kissResult
    let len;
    let data = new kissResult(null);
    // Deserialize message field [total_kiss_kissed]
    data.total_kiss_kissed = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learing/kissResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b6d67e0f2940c2fcc0bd08f43f03238e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #定义目标结果
    uint32 total_kiss_kissed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new kissResult(null);
    if (msg.total_kiss_kissed !== undefined) {
      resolved.total_kiss_kissed = msg.total_kiss_kissed;
    }
    else {
      resolved.total_kiss_kissed = 0
    }

    return resolved;
    }
};

module.exports = kissResult;
