// Auto-generated. Do not edit!

// (in-package learing.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class kissGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.kiss_id = null;
    }
    else {
      if (initObj.hasOwnProperty('kiss_id')) {
        this.kiss_id = initObj.kiss_id
      }
      else {
        this.kiss_id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type kissGoal
    // Serialize message field [kiss_id]
    bufferOffset = _serializer.uint32(obj.kiss_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type kissGoal
    let len;
    let data = new kissGoal(null);
    // Deserialize message field [kiss_id]
    data.kiss_id = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learing/kissGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6aea3f8f65c1fe428761a4336efff6c6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #定义目标信息
    uint32 kiss_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new kissGoal(null);
    if (msg.kiss_id !== undefined) {
      resolved.kiss_id = msg.kiss_id;
    }
    else {
      resolved.kiss_id = 0
    }

    return resolved;
    }
};

module.exports = kissGoal;
