// Auto-generated. Do not edit!

// (in-package learing.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class kissFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.kiss_complete = null;
    }
    else {
      if (initObj.hasOwnProperty('kiss_complete')) {
        this.kiss_complete = initObj.kiss_complete
      }
      else {
        this.kiss_complete = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type kissFeedback
    // Serialize message field [kiss_complete]
    bufferOffset = _serializer.float32(obj.kiss_complete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type kissFeedback
    let len;
    let data = new kissFeedback(null);
    // Deserialize message field [kiss_complete]
    data.kiss_complete = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learing/kissFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '908dd8fdbebbc138872a0182e5166b61';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #定义周期反馈信息
    float32 kiss_complete
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new kissFeedback(null);
    if (msg.kiss_complete !== undefined) {
      resolved.kiss_complete = msg.kiss_complete;
    }
    else {
      resolved.kiss_complete = 0.0
    }

    return resolved;
    }
};

module.exports = kissFeedback;
