(cl:defpackage learing-msg
  (:use )
  (:export
   "<KISSACTION>"
   "KISSACTION"
   "<KISSACTIONFEEDBACK>"
   "KISSACTIONFEEDBACK"
   "<KISSACTIONGOAL>"
   "KISSACTIONGOAL"
   "<KISSACTIONRESULT>"
   "KISSACTIONRESULT"
   "<KISSFEEDBACK>"
   "KISSFEEDBACK"
   "<KISSGOAL>"
   "KISSGOAL"
   "<KISSRESULT>"
   "KISSRESULT"
  ))

