; Auto-generated. Do not edit!


(cl:in-package learing-msg)


;//! \htmlinclude kissGoal.msg.html

(cl:defclass <kissGoal> (roslisp-msg-protocol:ros-message)
  ((kiss_id
    :reader kiss_id
    :initarg :kiss_id
    :type cl:integer
    :initform 0))
)

(cl:defclass kissGoal (<kissGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <kissGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'kissGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learing-msg:<kissGoal> is deprecated: use learing-msg:kissGoal instead.")))

(cl:ensure-generic-function 'kiss_id-val :lambda-list '(m))
(cl:defmethod kiss_id-val ((m <kissGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learing-msg:kiss_id-val is deprecated.  Use learing-msg:kiss_id instead.")
  (kiss_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <kissGoal>) ostream)
  "Serializes a message object of type '<kissGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'kiss_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'kiss_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'kiss_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'kiss_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <kissGoal>) istream)
  "Deserializes a message object of type '<kissGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'kiss_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'kiss_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'kiss_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'kiss_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<kissGoal>)))
  "Returns string type for a message object of type '<kissGoal>"
  "learing/kissGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'kissGoal)))
  "Returns string type for a message object of type 'kissGoal"
  "learing/kissGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<kissGoal>)))
  "Returns md5sum for a message object of type '<kissGoal>"
  "6aea3f8f65c1fe428761a4336efff6c6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'kissGoal)))
  "Returns md5sum for a message object of type 'kissGoal"
  "6aea3f8f65c1fe428761a4336efff6c6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<kissGoal>)))
  "Returns full string definition for message of type '<kissGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义目标信息~%uint32 kiss_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'kissGoal)))
  "Returns full string definition for message of type 'kissGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义目标信息~%uint32 kiss_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <kissGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <kissGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'kissGoal
    (cl:cons ':kiss_id (kiss_id msg))
))
