; Auto-generated. Do not edit!


(cl:in-package learing-msg)


;//! \htmlinclude kissFeedback.msg.html

(cl:defclass <kissFeedback> (roslisp-msg-protocol:ros-message)
  ((kiss_complete
    :reader kiss_complete
    :initarg :kiss_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass kissFeedback (<kissFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <kissFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'kissFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learing-msg:<kissFeedback> is deprecated: use learing-msg:kissFeedback instead.")))

(cl:ensure-generic-function 'kiss_complete-val :lambda-list '(m))
(cl:defmethod kiss_complete-val ((m <kissFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learing-msg:kiss_complete-val is deprecated.  Use learing-msg:kiss_complete instead.")
  (kiss_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <kissFeedback>) ostream)
  "Serializes a message object of type '<kissFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'kiss_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <kissFeedback>) istream)
  "Deserializes a message object of type '<kissFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'kiss_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<kissFeedback>)))
  "Returns string type for a message object of type '<kissFeedback>"
  "learing/kissFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'kissFeedback)))
  "Returns string type for a message object of type 'kissFeedback"
  "learing/kissFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<kissFeedback>)))
  "Returns md5sum for a message object of type '<kissFeedback>"
  "908dd8fdbebbc138872a0182e5166b61")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'kissFeedback)))
  "Returns md5sum for a message object of type 'kissFeedback"
  "908dd8fdbebbc138872a0182e5166b61")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<kissFeedback>)))
  "Returns full string definition for message of type '<kissFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义周期反馈信息~%float32 kiss_complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'kissFeedback)))
  "Returns full string definition for message of type 'kissFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义周期反馈信息~%float32 kiss_complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <kissFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <kissFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'kissFeedback
    (cl:cons ':kiss_complete (kiss_complete msg))
))
