controllers: {
  base_controller: {
    type: diff_controller,
    base_frame_id: base_footprint_link,
    base_width: 0.38,
    ticks_meter: 4100,
    Kp: 12,
    Kd: 12,
    Ki: 0,
    Ko: 20,
    accel_limit: 1.0
  }
}