<robot  name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="M_PI" value="3.1415926"/>

    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_length" value="0.0025"/>
    <xacro:property name="wheel_joint_y" value="0.19"/>
    <xacro:property name="wheel_joint_z" value="0.05"/>
    <xacro:property name="wheel_m" value="0.05"/>
    
    <xacro:property name="base_radius" value="0.20"/>
    <xacro:property name="base_length" value="0.16"/>
    <xacro:property name="base_m" value="0.5"/>
    
    <xacro:property name="caster_radius" value="0.015"/>
    <xacro:property name="caster_joint_x" value="0.18"/>
    <xacro:property name="caster_m" value="0.01"/>
    
    <!--Macro for inertia matrix-->
    <xacro:macro name="sphere_inertial_matrix" params="m  r">
        <inertial>
            <mass value="${m}"/>
           <inertia ixx="${2*m*r*r/5}" ixy="0.0" ixz="0.0" 
                    iyy="${2*m*r*r/5}" iyz="0.0" 
                    izz="${2*m*r*r/5}"/>
        </inertial>
    </xacro:macro>

     <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}"/>
           <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0.0" ixz="0.0" 
                    iyy="${m*(3*r*r+h*h)/12}" iyz="0.0" 
                    izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>

     <xacro:macro name="box_inertial_matrix" params="m l w h">
        <inertial>
            <mass value="${m}"/>
           <inertia ixx="${m*(h*h+l*l)/12}" ixy="0.0" ixz="0.0" 
                    iyy="${m*(w*w+l*l)/12}" iyz="0.0" 
                    izz="${m*(w*w+l*l)/12}"/>
        </inertial>
    </xacro:macro>

    <material name="yellow">
        <color rgba="1.0 0.4 0.0 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1.0"/>
    </material>

    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0.0 ${reflect*wheel_joint_y}  -${wheel_joint_z}" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>

        <transmission name="${prefix}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_joint_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </actuator>
        </transmission>
    
        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Red</material>
        </gazebo>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="gray"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
        <xacro:cylinder_inertial_matrix m="${wheel_m}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>
    </xacro:macro>
    <xacro:wheel prefix="left" reflect="1"/>
    <xacro:wheel prefix="right" reflect="-1"/>
    
    <xacro:macro name="caster" params="prefix reflect">
       <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="${reflect* caster_joint_x} 0.0 -${base_length/2+caster_radius}" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0.0 1.0 0.0"/>
       </joint>
        
        <gazebo reference="${prefix}_caster_link">
            <material> Gazebo/Red</material>
        </gazebo>

       <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="${caster_radius}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="${caster_radius}"/>
                </geometry>
            </collision>
        <xacro:sphere_inertial_matrix m="${caster_m}" r="${caster_radius}"/>
       </link>
    </xacro:macro>
    <xacro:caster prefix="front" reflect="1"/>
    <xacro:caster prefix="back" reflect="-1"/>
    

    <xacro:macro name="mbot_base">
        <link name="base_footprint_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
            </collision>
           
        <xacro:box_inertial_matrix m="0.01" l="0.001" w="0.001" h="0.001"/>
        </link>

        <gazebo reference="base_link">
            <material>Gazebo/Yellow</material>
        </gazebo>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0.0 0.0 ${base_length/2+caster_radius*2}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint_link"/>
            <child link="base_link"/>
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${base_radius}" length="${base_length}"/>
                </geometry>
                <material name="yellow"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${base_radius}" length="${base_length}"/>
                </geometry>
            </collision>
        <xacro:cylinder_inertial_matrix m="${base_m}" r="${base_radius}" h="${base_length}"/>
        </link>
    </xacro:macro>
</robot>
